### PR TITLE
Various improvements

### LINKED ISSUE #20: Fix build on supported Python versions
Installing requirements fails on Python 3.10.15 and 3.9.20:

```bash
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 23))
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-gp8almpx/markupsafe_b7e8500dfa364d319c821defd9d09367/setup.py", line 6, in <module>
          from setuptools import setup, Extension, Feature
      ImportError: cannot import name 'Feature' from 'setuptools' (/home/ddewhurst/google_drive/Repositories/co-op/os4d/.venv/lib/python3.10/site-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

We should get the build working on supported Python versions (3.9+) - we may as well get it working 3.13 as it will be supported the longest.

### LINKED ISSUE #51: Can we use co-op Sphinx theme?
Just discussed with @mollieodsc 

Can OS4D use the co-ops Sphinx theme?

This is here: https://github.com/OpenDataServices/odsc_default_sphinx_theme 

An example can be seen here: https://flatten-tool.readthedocs.io/en/latest/

It would hopefully be a pretty small commit: https://github.com/OpenDataServices/flatten-tool/commit/ba814d06156379045afb60975994a4af03577e99 

No particular rush, but we are aware @duncandewhurst is working on OS4D and we wanted to mention this now in case there were other things planned for the look.

### PR DESCRIPTION
**Pull request by duncandewhurst**
* Closes #20 (build succeeds on Python 3.13.0)
* Closes #51

Makes various improvements aimed at making OS4D easier to read, maintain and contribute to:

* Build on ReadtheDocs: https://os4d--41.org.readthedocs.build/
* Switch to MyST Parser
* Switch to ODS default Sphinx theme
* Switch to Mermaid for charts
* Move TO DOs from Markdown files to GitHub issues
* Use implicit targets
* Format Markdown files
* Remove empty headings
* Replace some links with see also admonitions
* Fix linkcheck GitHub Actions workflow
* Correct spelling and grammar errors

### CODE REVIEW

**Comment by jarofgreen** [comment]
I dropped a commit on; lintcheck would have failed to run due to an old version if I hadn't

**Comment by jarofgreen** [comment]
requirements_dev.txt - technically the contents of this file should be a in requirements_dev.in. The txt file should be the locked version. And the .in file should have a reference to the non-dev requirements. We can issue that for later tho.

**Comment by jarofgreen** [comment]
This sets up RTD hosting - we already have hosting for this, and having 2 hosts can cause problems (I see the new project on RTD too). Can we pull that from this PR and come back to the hosting issue later?

**Comment by duncandewhurst** [comment]
I am happy to remove it if https://github.com/OpenDataServices/os4d/issues/14 can be addressed (instructions on how to deploy to the existing hosting)

**Comment by jarofgreen** [comment]
Commented in https://github.com/OpenDataServices/os4d/issues/14#issuecomment-2714701833 - we'll address readme in different PR

**Review by jarofgreen — APPROVED** [review]
