### ISSUE TITLE
Fix build on supported Python versions

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/os4d#20]
Installing requirements fails on Python 3.10.15 and 3.9.20:

```bash
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 23))
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-gp8almpx/markupsafe_b7e8500dfa364d319c821defd9d09367/setup.py", line 6, in <module>
          from setuptools import setup, Extension, Feature
      ImportError: cannot import name 'Feature' from 'setuptools' (/home/ddewhurst/google_drive/Repositories/co-op/os4d/.venv/lib/python3.10/site-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

We should get the build working on supported Python versions (3.9+) - we may as well get it working 3.13 as it will be supported the longest.

**Comment by duncandewhurst** [comment]
Done in #41
